### ISSUE TITLE
Docker Compose Environment File Non-existent

### ISSUE THREAD

**Issue by nickbabcock** [mitre/cedar#3]
``` bash
$ sudo docker-compose up
ERROR: Couldn't find env file: /home/nick/projects/cedar/.env-prod
```

Because in `docker-compose.yml`

``` yaml
cedar:
  # ...
  env_file: .env-prod
```

`.env-prod` does not exist, thus docker-compose fails to work.

I worked around the issue by supplying a custom environment

``` yaml
cedar:
  environment:
    SECRET_KEY_BASE: "bobbytables"
```

In general, docker should default to the development environment and when targeting production, [supply an additional docker compose file](https://docs.docker.com/compose/production/)
